# SPDX-License-Identifier: BSD-2-Clause
# Loaded after project(okular), before target dependencies are discovered.

if(NOT CMAKE_CROSSCOMPILING)
    message(FATAL_ERROR "The toolchain must cross-compile: set CMAKE_SYSTEM_NAME=${OKULAR_CROSS_SYSTEM} in the toolchain.")
endif()
if(NOT CMAKE_SYSTEM_NAME STREQUAL OKULAR_CROSS_SYSTEM)
    message(FATAL_ERROR "The toolchain must cross-compile for ${OKULAR_CROSS_SYSTEM}; got ${CMAKE_SYSTEM_NAME}.")
endif()
if(OKULAR_CROSS_ARCH STREQUAL "arm64")
    set(_okular_processors arm64 aarch64)
else()
    set(_okular_processors x86_64 AMD64 amd64)
endif()
if(NOT CMAKE_SYSTEM_PROCESSOR IN_LIST _okular_processors)
    message(FATAL_ERROR "The toolchain processor must match --arch ${OKULAR_CROSS_ARCH}; got ${CMAKE_SYSTEM_PROCESSOR}.")
endif()
if(APPLE AND NOT CMAKE_OSX_ARCHITECTURES STREQUAL OKULAR_CROSS_ARCH)
    message(FATAL_ERROR "Set CMAKE_OSX_ARCHITECTURES=${OKULAR_CROSS_ARCH} in the toolchain.")
endif()
if(NOT CMAKE_FIND_ROOT_PATH AND NOT CMAKE_SYSROOT AND NOT CMAKE_OSX_SYSROOT)
    message(FATAL_ERROR "The toolchain must specify target search roots or an SDK/sysroot.")
endif()
set(CMAKE_FIND_ROOT_PATH_MODE_PROGRAM NEVER)
set(CMAKE_FIND_ROOT_PATH_MODE_LIBRARY ONLY)
set(CMAKE_FIND_ROOT_PATH_MODE_INCLUDE ONLY)
set(CMAKE_FIND_ROOT_PATH_MODE_PACKAGE ONLY)
set(CMAKE_FIND_USE_PACKAGE_REGISTRY OFF)
set(CMAKE_FIND_USE_SYSTEM_PACKAGE_REGISTRY OFF)
set(ENV{PKG_CONFIG_PATH} "")
if(NOT DEFINED ENV{PKG_CONFIG_LIBDIR})
    set(ENV{PKG_CONFIG_LIBDIR} "")
endif()
foreach(_path QT_HOST_PATH KF6_HOST_TOOLING)
    if(NOT IS_DIRECTORY "${${_path}}")
        message(FATAL_ERROR "Set ${_path} to matching Linux host tools using a CMake -D definition or the toolchain.")
    endif()
endforeach()
